### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by kzkpro** [killercrush/music-tempo#1]
Hi i'm getting following error for few tracks.
re[_k] = hammWindow[_k] * audioData[i];
                                                ^

RangeError: Invalid string length
    at Float32Array.join (native)
    at Float32Array.toString (native)

in **/music-tempo/dist/node/OnsetDetection.js:116:49

can you please let me know how to fix it? thanks!

**Comment by killercrush** [comment]
Hi @kzkpro, can you send the tracks that cause the error ??

**Comment by kzkpro** [comment]
@killercrush , here's track http://nepwebsolutions.com/drums.mp3 and thanks for quick reply!

**Comment by killercrush** [comment]
@kzkpro, I fixed the issue, but still, for this track you have to pass parameter `expiryTime`, because track contains periods of silence. Something like this: `var mt = new MusicTempo(audioData, {expiryTime: 30});`.

**Comment by kzkpro** [comment]
Thanks @killercrush
