### ISSUE TITLE
This doesn't work (BPM is incorrect)

### ISSUE THREAD

**Issue by tcarroll2** [killercrush/music-tempo#11]
I tried using your test page to get the BPM of the song "Say Something" by A Big World (feat. Christina Aguilera).  Your test page shows that song has a BPM of 131.  That BPM is way, way, too high for that song.  That song actually has a BPM of about 50.

**Comment by killercrush** [comment]
Looks like BPM of the song is 141
https://tunebat.com/Info/Say-Something-A-Great-Big-World-Christina-Aguilera/6Vc5wAMmXdKIAM7WUoEb7N

**Comment by tcarroll2** [comment]
Yeah, I see that too.  I guess the BPM calculation has changed since I last looked at BPM's.  Thanks for the update!
