### ISSUE TITLE
How to get echo tone?

### ISSUE THREAD

**Issue by weathon** [killercrush/music-tempo#2]
I have read the document, but I still don't know how to get echo tone, like the demo app
https://killercrush.github.io/music-tempo/example/example-advanced.html
It can get every tone note and their loudness, time and frequency.

**Comment by weathon** [comment]
@killercrush

**Comment by weathon** [comment]
I meanhow to get the Spectrogram

**Comment by killercrush** [comment]
This library is intended only to determine the tempo of music. 
In the demo app I used java-library TarsosDSP to calculate the spectrogram (Constant Q). To convert java to javascript I used JSweet.

**Comment by weathon** [comment]
Can I get that code, please?

**Comment by killercrush** [comment]
https://github.com/killercrush/music-tempo/tree/master/example/lib

**Comment by weathon** [comment]
Thanks
