### ISSUE TITLE
Differences between music-tempo and Beatroot

### ISSUE THREAD

**Issue by joelle-o-world** [killercrush/music-tempo#3]
Hello,

I hope you don't mind answering a nerdy question.

In the [paper linked in the readme ](http://www.eecs.qmul.ac.uk/~simond/pub/2001/jnmr.pdf) it appears that Beatroot uses mean-absolute-peaks for onset detection, whereas I see music-tempo is using spectral flux. 

I wondered whether there are any other developments on Dixon's algorithm at play in this library?

Thanks so much,
Joel

**Comment by killercrush** [comment]
Hello. There should be no significant differences between this library and Dixon's BeatRoot java app - http://www.eecs.qmul.ac.uk/~simond/beatroot/
The spectral flux is described here - http://www.eecs.qmul.ac.uk/~simond/pub/2007/jnmr07.pdf

**Comment by joelle-o-world** [comment]
Ahh, thank you!! I hadn't seen that second paper!
