### ISSUE TITLE
Different (inaccurate) results on mobile vs desktop.

### ISSUE THREAD

**Issue by Leftium** [killercrush/music-tempo#5]
I made a beat-aware media player using music-tempo: https://phrasier.leftium.com/

It works great on desktop, however the results are not quite right on mobile browsers. The tempo should be 119 BPM, but mobile browsers result in 107 BPM. The actual beat timings are off, too. Both mobile and desktop agree on the total number of beats, though.

I think music-tempo does a deterministic analysis of the audio data, so I'm not sure how mobile and desktop results could diverge. Does music-tempo change the number of tests or cut tests short depending on the performance of the system?

**Comment by killercrush** [comment]
No, music-tempo does not change behavior depending on the perfomance of the system.
I think the results vary due to differences in hardware and/or browsers implementations of the math functions (cos, sqrt)
P.S. I followed your link in a desktop browser (Chrome 80) and got 107 BPM

**Comment by Leftium** [comment]
@killercrush can you describe your hardware/environment? I've only been able to reproduce on mobile.

**Minimal repro steps using only example from music-tempo:**
1. Download this video file: http://phrasier.leftium.com/media/video.mp4
2. Process it with https://killercrush.github.io/music-tempo/example/example-simple.html
3. Inspect output in DevTools Console

**Expected tempo:** 119
**Actual tempo:** 107

---

https://phrasier.leftium.com also logs results from `MusicTempo()` to the dev console. (And I just found out you can right-click "Store as global variable"). Almost none of the data seems to match.

I published the beats arrays for both:
- [119 BPM Beats (Desktop)](https://codebeautify.org/jsonviewer/cb3356ec)
- [107 BPM Beats (Mobile)](https://codebeautify.org/jsonviewer/cba1ed77)

Interestingly, both have the exact same number of beats, but the 107 BPM has beats that occur at 130 seconds when the video is only 119 seconds long.

**Comment by killercrush** [comment]
I figured out what the problem is. You need to create AudioContext with sampleRate config:
`      var context = new AudioContext({
        sampleRate: 44100
      });
`
44100 is a common sample rate value in mp3 files.
This [answer](https://stackoverflow.com/questions/56270593/audiocontext-decodeaudiodata-seems-to-create-crackling-noise) on stackoverflow describes the cause of the problem.
