### ISSUE TITLE
Bad beats

### ISSUE THREAD

**Issue by elibarzilay** [killercrush/music-tempo#8]
This is probably similar to #5 in that the bottom line is that I got the same number of beats, and even roughly at similar places, but the end result sounded horrible.  (To debug it I recreated parts of your test page code with the ticker thing.)

But in this case I finally figured that something is off with `web-audio-api` on node: once I repeated things in a browser, it finally worked as it should.  For reference, I'm attaching the file with the beats for both.

Also, the code I used with node -- which didn't work (adding `sampleRate` makes no difference) is:

```js
const fs = require("fs");
const MusicTempo = require("music-tempo");
const AudioContext = require("web-audio-api").AudioContext;

const calcTempo = async file => {
  const data = fs.readFileSync(file);
  const buff = await new Promise((res,rej) => (new AudioContext()).decodeAudioData(data, res, rej));
  const buf0 = buff.getChannelData(0);
  const buf1 = buff.getChannelData(buff.numberOfChannels > 1 ? 1 : 0);
  const audioData = buf0.map((n0, i) => (n0 + buf1[i])/2);
  const mt = new MusicTempo(audioData);
  console.log(mt.tempo);
  console.log(mt.beats);
}
```

and in a browser:

```js
fetch($player.src)
  .then(x => x.arrayBuffer())
  .then(x => (new AudioContext()).decodeAudioData(x))
  .then(x => {
    const c1 = x.getChannelData(0), c2 = x.getChannelData(1), 
          c = c1.map((x,i) => (x+c2[i])/2),
          mt = new MusicTempo(c);
    console.log(mt.beats);
  });
```

Maybe there's some problem with `w-a-a`, but I followed your readme, so adding a warning might be good...

**Comment by elibarzilay** [comment]
[R.js.gz](https://github.com/killercrush/music-tempo/files/6767157/R.js.gz)

**Comment by parallax4** [comment]
@elibarzilay @killercrush Any idea on what's causing this discrepancy? I'd like to use the Node version, if possible.

**Comment by killercrush** [comment]
@parallax4 I need the audio file with which I can reproduce the problem
